#!/usr/bin/env python3
"""Hand-made pixel-art soldier sprites for stage 8.

Every sprite is 16x16, the same as a soldier's hitbox. Five poses are
drawn here (facing N, NE, E, SE, S), two walk frames each; the game
mirrors E, NE and SE to get W, NW and SW. Each character is one pixel:

    .  transparent        H  hair            B  bandana (gang colour)
    S  skin               T  shirt (gang)    D  shirt shadow
    P  pants              F  shoes           G  chain (Big Homie only)
    a  gun (pistol and shotgun)   b  gun barrel (shotgun only)
    k  knife

The palette index of each letter is its position in LETTERS; the
game picks the colours per soldier (gang, skin tone, weapon).

    python3 tools/gen_sprites.py --write 01_sprites.asm
    python3 tools/gen_sprites.py --preview sprites.png   # needs PIL
    python3 tools/gen_sprites.py --preview-objects objects.png
"""
import sys

LETTERS = ".HBSTDPFGabk"   # index 0..11

POSES = {}
POSES['S'] = ["""
................
......BBBB......
.....BBBBBB.....
.....HHHHHH.....
.....HSSSSH.....
......SSSS......
....DTTGGTTD....
...DTTTTTTTTD...
...STTTTTTTTS...
...STTTTTTTTS...
...S.TTTTTT.S...
..ak.PPPPPP.....
..ak.PP..PP.....
..b..PP..PP.....
..b..FF..FF.....
................
""", """
................
......BBBB......
.....BBBBBB.....
.....HHHHHH.....
.....HSSSSH.....
......SSSS......
....DTTGGTTD....
...DTTTTTTTTD...
...STTTTTTTTS...
...STTTTTTTTS...
...S.TTTTTT.S...
..ak.PPPPPP.....
..ak.PP..PP.....
..b..PP..FF.....
..b..FF.........
................
"""]
POSES['N'] = ["""
................
......HHHH......
.....HHHHHH.....
.....HHBBHH.....
.....HHHHHH.....
......HHHH......
....DTTTTTTD..b.
...DTTTTTTTTDab.
...STTTTTTTTSak.
...STTTTTTTTS.k.
...S.TTTTTT.S...
.....PPPPPP.....
.....PP..PP.....
.....PP..PP.....
.....FF..FF.....
................
""", """
................
......HHHH......
.....HHHHHH.....
.....HHBBHH.....
.....HHHHHH.....
......HHHH......
....DTTTTTTD..b.
...DTTTTTTTTDab.
...STTTTTTTTSak.
...STTTTTTTTS.k.
...S.TTTTTT.S...
.....PPPPPP.....
.....PP..PP.....
.....FF..PP.....
.........FF.....
................
"""]
POSES['E'] = ["""
................
......BBBB......
.....BBBBBH.....
.....HHHHSS.....
.....HHHHSS.....
......HHSS......
......TTGT......
.....DTTTTT.....
.....DTTTTTSSakb
.....DTTTTT..k..
......TTTT......
......PPPP......
.....PP..PP.....
.....PP...PP....
.....FF...FF....
................
""", """
................
......BBBB......
.....BBBBBH.....
.....HHHHSS.....
.....HHHHSS.....
......HHSS......
......TTGT......
.....DTTTTT.....
.....DTTTTTSSakb
.....DTTTTT..k..
......TTTT......
......PPPP......
......PPP.......
......PPP.......
......FFF.......
................
"""]
POSES['SE'] = ["""
................
.......BBBB.....
......BBBBBB....
......HHHHSH....
......HSSSSS....
.......SSSS.....
.....DTTGGTT....
....DTTTTTTTS...
....TTTTTTTTSS..
....STTTTTTT.ak.
.....TTTTTT...ak
......PPPPP....b
......PP..PP....
.....PP....PP...
.....FF.....FF..
................
""", """
................
.......BBBB.....
......BBBBBB....
......HHHHSH....
......HSSSSS....
.......SSSS.....
.....DTTGGTT....
....DTTTTTTTS...
....TTTTTTTTSS..
....STTTTTTT.ak.
.....TTTTTT...ak
......PPPPP....b
......PPPPP.....
.......PPP......
.......FFF......
................
"""]
POSES['NE'] = ["""
...............b
.......HHHH...a.
......HHHHHH.ak.
......HBBHHHak..
......HHHHHS....
.......HHHS.....
.....DTTTTTTS...
....DTTTTTTTSS..
....TTTTTTTT....
....STTTTTTT....
.....TTTTTT.....
......PPPPP.....
......PP..PP....
.....PP....PP...
.....FF.....FF..
................
""", """
...............b
.......HHHH...a.
......HHHHHH.ak.
......HBBHHHak..
......HHHHHS....
.......HHHS.....
.....DTTTTTTS...
....DTTTTTTTSS..
....TTTTTTTT....
....STTTTTTT....
.....TTTTTT.....
......PPPPP.....
......PPPPP.....
.......PPP......
.......FFF......
................
"""]
ORDER = ['N', 'NE', 'E', 'SE', 'S']   # sprite number = pose * 2 + frame


# ---------------------------------------------------------------------
# 8.02: objects. Each family has its own letters (palette indices).
# ---------------------------------------------------------------------

# Cars, 40x20, facing east (front on the right). Parked cars are drawn
# from this into the background by gen_neighborhood.py, in their own
# colours; vertical ones are it turned to face south.
#   K body   k body edge   W glass   w side glass   R tail light
#   L headlight   X tyre   U roof (the police car's white)
CAR_LETTERS = ".KkWwRLXUrb"
CAR_ART = """
......XXXXXX................XXXXXX......
..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
.kKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk.
RKKKKKKKkwwwwwwwwwwwwwwwwwwwwkKKKKKKKKKL
RKKKKKKkWWkKKKKKKKKKKKKKKKKKkWWWWkKKKKKL
kKKKKKKkWWkKKKKKKKKKKKKKKKKKkWWWWWkKKKKk
kKKKKKKkWWkKKKKKKKKKKKKKKKKKkWWWWWkKKKKk
kKKKKKKkWWkKKKKKKKKKKKKKKKKKkWWWWWkKKKKk
kKKKKKKkWWkKKKKKKKKKKKKKKKKKkWWWWWkKKKKk
kKKKKKKkWWkKKKKKKKKKKKKKKKKKkWWWWWkKKKKk
kKKKKKKkWWkKKKKKKKKKKKKKKKKKkWWWWWkKKKKk
kKKKKKKkWWkKKKKKKKKKKKKKKKKKkWWWWWkKKKKk
kKKKKKKkWWkKKKKKKKKKKKKKKKKKkWWWWWkKKKKk
kKKKKKKkWWkKKKKKKKKKKKKKKKKKkWWWWWkKKKKk
kKKKKKKkWWkKKKKKKKKKKKKKKKKKkWWWWWkKKKKk
RKKKKKKkWWkKKKKKKKKKKKKKKKKKkWWWWkKKKKKL
RKKKKKKKkwwwwwwwwwwwwwwwwwwwwkKKKKKKKKKL
.kKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk.
..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
......XXXXXX................XXXXXX......
"""
# the police car: white roof and doors, a light bar (r / b swap colours)
COP_ART = """
......XXXXXX................XXXXXX......
..kkkkkkkkkkUUUUUUUUUUUUUUUUUkkkkkkkkk..
.kKKKKKKKKKKUUUUUUUUUUUUUUUUUKKKKKKKKKk.
RKKKKKKKkwwwwwwwwwwwwwwwwwwwwkKKKKKKKKKL
RKKKKKKkWWkUUUUUUUUUUUUUUUUUkWWWWkKKKKKL
kKKKKKKkWWkUUUUUUUUUUUUUUUUUkWWWWWkKKKKk
kKKKKKKkWWkUUUUUUrrrrUUUUUUUkWWWWWkKKKKk
kKKKKKKkWWkUUUUUUrrrrUUUUUUUkWWWWWkKKKKk
kKKKKKKkWWkUUUUUUrrrrUUUUUUUkWWWWWkKKKKk
kKKKKKKkWWkUUUUUUbbbbUUUUUUUkWWWWWkKKKKk
kKKKKKKkWWkUUUUUUbbbbUUUUUUUkWWWWWkKKKKk
kKKKKKKkWWkUUUUUUbbbbUUUUUUUkWWWWWkKKKKk
kKKKKKKkWWkUUUUUUUUUUUUUUUUUkWWWWWkKKKKk
kKKKKKKkWWkUUUUUUUUUUUUUUUUUkWWWWWkKKKKk
kKKKKKKkWWkUUUUUUUUUUUUUUUUUkWWWWWkKKKKk
RKKKKKKkWWkUUUUUUUUUUUUUUUUUkWWWWkKKKKKL
RKKKKKKKkwwwwwwwwwwwwwwwwwwwwkKKKKKKKKKL
.kKKKKKKKKKKUUUUUUUUUUUUUUUUUKKKKKKKKKk.
..kkkkkkkkkkUUUUUUUUUUUUUUUUUkkkkkkkkk..
......XXXXXX................XXXXXX......
"""

# The dog, 16x16 (most of it empty), facing east, two running frames.
#   D body   E ear   N nose   T tail   L legs   C collar
DOG_LETTERS = ".DENTLC"
DOG_ART = ["""
................
................
................
................
...........EE...
..........DDDDN.
.T........CDDD..
..TDDDDDDDCDD...
...DDDDDDDDD....
...DDDDDDDDD....
...L.L....L.L...
...L.L....L.L...
................
................
................
................
""", """
................
................
................
................
...........EE...
..........DDDDN.
T.........CDDD..
.TTDDDDDDDCDD...
...DDDDDDDDD....
...DDDDDDDDD....
....LL...LL.....
...L....L..L....
................
................
................
................
"""]

# Weapon pickups, 16x16: a dark gun with an outline in the pickup's
# colour (pistol yellow, shotgun magenta, as the old squares were).
#   o outline   G metal   g metal highlight   W wooden stock
PICKUP_LETTERS = ".oGgW"
PICKUP_ART = ["""
................
................
................
................
...oooooooooo...
...oGGGGGGGGGo..
...oGgggggggGo..
...oGGGGooooo...
...oGGGo........
...oGGGo........
...oGGo.........
...oooo.........
................
................
................
................
""", """
................
................
................
................
................
oooooooooooooooo
oWWWWGGGGGGGGGGo
oWWWWGgggggggggo
oWWWoGGGoooooooo
oWWo.oGo........
oooo.ooo........
................
................
................
................
................
"""]


def art_grid(art, letters, w, h):
    rows = art.strip('\n').split('\n')
    assert len(rows) == h, f"{len(rows)} rows, want {h}"
    for r in rows:
        assert len(r) == w, f"row {r!r} is {len(r)} wide, want {w}"
        for c in r:
            assert c in letters, f"unknown pixel {c!r}"
    return [[letters.index(c) for c in r] for r in rows]


def rotate_cw(g):
    """east-facing -> south-facing (front at the bottom)"""
    h, w = len(g), len(g[0])
    return [[g[h - 1 - y][x] for y in range(h)] for x in range(w)]


def object_blocks():
    """(label, comment, grids) for every object sprite"""
    car_h = art_grid(COP_ART, CAR_LETTERS, 40, 20)
    return [
        ("cop_sprite_h", "the police car, 40x20, facing east", [car_h]),
        ("cop_sprite_v", "the police car, 20x40, facing south", [rotate_cw(car_h)]),
        ("dog_sprites", "the dog, 16x16, facing east, two frames", [art_grid(a, DOG_LETTERS, 16, 16) for a in DOG_ART]),
        ("pickup_sprites", "pickups, 16x16: pistol, then shotgun", [art_grid(a, PICKUP_LETTERS, 16, 16) for a in PICKUP_ART]),
    ]


# ---------------------------------------------------------------------
# 8.03: props, drawn into the background by gen_neighborhood.py.
# ---------------------------------------------------------------------

# A tree canopy from above, 22x22: dark edge, leaves, sunlit clumps.
#   O edge   L leaves   l light leaves   d dark leaves
TREE_LETTERS = ".OLld"
TREE_ART = """
........OOOOOO........
......OOLLLLLLOO......
.....OLllLLLLLLLO.....
....OLllllLLLdLLLO....
...OLLlllLLLLLLLLLO...
..OLLLllLLLLdLLLLLLO..
..OLLLLLLLLLLLLllLLO..
.OLdLLLLLLllLLlllLLLO.
.OLLLLLLLlllLLLlLLLdO.
OLLLLlLLLLllLLLLLLLLLO
OLLLlllLLLLLLLLdLLLLLO
OLLLLlLLLLLLLLLLLLLLLO
OLLLLLLLLdLLLLlllLLLdO
OLLdLLLLLLLLLLLlLLLLLO
.OLLLLLllLLLLLLLLLLLO.
.OLLLLlllLLLLdLLLLLdO.
..OLLLLlLLLLLLLLLLdO..
..OLLLLLLLLLllLLLddO..
...OLLdLLLLLlLLLLdO...
....OLLLLLLLLLLddO....
.....OOLLLLLLdddO.....
.......OOOOOOOO.......
"""

# A bush, 10x10, the same letters.
BUSH_ART = """
...OOOO...
..OlLLLO..
.OllLLdLO.
OLlLLLLLdO
OLLLLdLLdO
OLLLLLLLdO
.OLLdLLddO
.OLLLLLdO.
..OOddOO..
....OO....
"""

# A dumpster, 26x16, lid seen from above.
#   G body   g body shadow   H hinge   h handle   W wheel   R rust
DUMPSTER_LETTERS = ".GgHhWR"
DUMPSTER_ART = """
.W......................W.
gggggggggggggggggggggggggg
gGGGGGGGGGGGgGGGGGGGGGGGGg
gGGGGGGGGGGGgGGGGRRGGGGGGg
gGGhhhGGGGGGgGGGGGRGGhhhGg
gGGGGGGGGGGGgGGGGGGGGGGGGg
gGGGGGGGGGGGgGGGGGGGGGGGGg
gGGGGGRGGGGGgGGGGGGGGGGGGg
gGGGGGGGGGGGgGGGGGGGGGGGGg
gGGGGGGGGGGGgGGGGGGGGGGGGg
gGGGGGGGGGGGgGGGGGGGGGGGGg
gGGGGGGGGGGGgGGGGGGGGGGGGg
gHHHHHHHHHHHHHHHHHHHHHHHHg
gggggggggggggggggggggggggg
.W......................W.
..........................
"""

# A rooftop air conditioner, 12x10: a box with a round fan grille.
#   B box   b box edge   F fan   f fan hub
AC_LETTERS = ".BbFf"
AC_ART = """
bbbbbbbbbbbb
bBBBBBBBBBBb
bBBBFFFFBBBb
bBBFFFFFFBBb
bBBFFffFFBBb
bBBFFffFFBBb
bBBFFFFFFBBb
bBBBFFFFBBBb
bBBBBBBBBBBb
bbbbbbbbbbbb
"""

# A streetlight from above, 8x8: the lamp head on its arm.
#   P pole   A arm   H lamp housing   G lamp glass
LIGHT_LETTERS = ".PAHG"
LIGHT_ART = """
..HHHH..
.HGGGGH.
.HGGGGH.
..HHHH..
...AA...
...AA...
..PPPP..
..PPPP..
"""


def prop_grids():
    return {
        'tree': art_grid(TREE_ART, TREE_LETTERS, 22, 22),
        'bush': art_grid(BUSH_ART, TREE_LETTERS, 10, 10),
        'dumpster': art_grid(DUMPSTER_ART, DUMPSTER_LETTERS, 26, 16),
        'ac': art_grid(AC_ART, AC_LETTERS, 12, 10),
        'light': art_grid(LIGHT_ART, LIGHT_LETTERS, 8, 8),
    }


# ---------------------------------------------------------------------
# 8.04: the ground remembers. A fallen soldier (soldier letters, so the
# game colours it by gang), blood splats and pools (letters ".rRd":
# mid red, bright red, dark red), all blended 50/50 with the ground.
# ---------------------------------------------------------------------
DEAD_ART = """
................
................
................
................
................
.....SS.........
.BBHHSTTTTTPPPF.
BBHHHTTTTTTPPPPF
BBHHHTTTTTTPPPPF
.BHHSSTTTTTPPPF.
.....SS.........
................
................
................
................
................
"""
BLOOD_LETTERS = ".rRd"
SPLAT_ART = ["""
............
.....r......
....rRr..r..
...rRRRr....
..rRRRRRr...
...rRRRRr...
..r.rRRr....
.....rr..r..
............
....r.......
............
............
""", """
............
..r.........
...rr...r...
...rRRr.....
....RRRRr...
...rRRRRRr..
....rRRRr...
.r...rRr....
.......r....
...r........
............
............
""", """
............
.......r....
..r..rr.....
....rRRr....
...rRRRRr.r.
..rRRdRRr...
...rRRRr....
....rrr.....
.r......r...
............
............
............
""", """
............
............
....r.r.....
...rRRRr....
..rRRRRRr...
.rRRRdRRRr..
..rRRRRRr...
...rRRRr....
....r..r....
...r....r...
............
............
"""]
POOL_ART = ["""
................
................
.....rrrrr......
...rrRRRRRrr....
..rRRRRRRRRRr...
.rRRRRdddRRRRr..
.rRRRddddddRRRr.
rRRRRddddddRRRr.
.rRRRRddddRRRRr.
..rRRRRRRRRRRr..
...rrRRRRRRrr...
.....rrrrrr.....
.......r........
................
................
................
""", """
................
................
......rrrr......
....rrRRRRr.....
..rrRRRRRRRr....
.rRRRRdddRRRr.r.
.rRRRdddddRRRr..
..rRRddddddRRRr.
..rRRRddddRRRRr.
...rRRRRRRRRRr..
..r.rrRRRRrr....
......rrrr......
................
................
................
................
"""]


def ground_blocks():
    return [
        ("dead_sprite", "a fallen soldier, 16x16, soldier letters (head west)",
         [art_grid(DEAD_ART, LETTERS, 16, 16)]),
        ("splat_sprites", "blood splats, 12x12, four shapes", [art_grid(a, BLOOD_LETTERS, 12, 12) for a in SPLAT_ART]),
        ("pool_sprites", "blood pools, 16x16, two shapes", [art_grid(a, BLOOD_LETTERS, 16, 16) for a in POOL_ART]),
    ]


def grid(art):
    rows = [r for r in art.strip('\n').split('\n')]
    assert len(rows) == 16, f"{len(rows)} rows"
    for r in rows:
        assert len(r) == 16, f"row {r!r} is {len(r)} wide"
        for c in r:
            assert c in LETTERS, f"unknown pixel {c!r}"
    return rows


def sprites():
    out = []
    for pose in ORDER:
        for art in POSES[pose]:
            out.append([[LETTERS.index(c) for c in row] for row in grid(art)])
    return out


def nasm():
    lines = [";; ---- SPRITE DATA (generated by tools/gen_sprites.py; don't edit by hand) ----",
             "    ; 16x16 palette indices, one byte per pixel; sprite = pose * 2 + walk frame,",
             "    ; poses " + ", ".join(ORDER) + " (W, NW, SW are E, NE, SE mirrored)",
             "    soldier_sprites:"]
    for n, sp in enumerate(sprites()):
        lines.append(f"        ; {ORDER[n // 2]} frame {n % 2}")
        for row in sp:
            lines.append("        db " + ",".join(str(v) for v in row))
    lines.append("    SPRITE_COUNT equ ($ - soldier_sprites) / 256")
    for label, comment, grids in object_blocks() + ground_blocks():
        lines.append(f"    ; {comment}")
        lines.append(f"    {label}:")
        for g in grids:
            for row in g:
                lines.append("        db " + ",".join(str(v) for v in row))
    lines.append(";; ---- END SPRITE DATA ----")
    return "\n".join(lines)


def preview_objects(path):
    from PIL import Image
    cols = {'car': {1: (20, 20, 20), 2: (60, 60, 60), 3: (60, 80, 110), 4: (80, 100, 130), 5: (200, 30, 30),
                    6: (255, 240, 180), 7: (10, 10, 10), 8: (240, 240, 240), 9: (230, 30, 30), 10: (40, 80, 255)},
            'dog': {1: (160, 100, 60), 2: (110, 65, 40), 3: (20, 20, 20), 4: (160, 100, 60), 5: (110, 65, 40), 6: (200, 30, 30)},
            'pick': {1: (230, 210, 40), 2: (50, 50, 55), 3: (110, 110, 115), 4: (130, 80, 40)}}
    fam = {'cop_sprite_h': 'car', 'cop_sprite_v': 'car', 'dog_sprites': 'dog', 'pickup_sprites': 'pick'}
    scale = 6
    im = Image.new("RGB", (190 * scale, 45 * scale), (96, 140, 78))
    px = im.load()
    ox = 1
    for label, _, grids in object_blocks():
        for g in grids:
            for y, row in enumerate(g):
                for x, v in enumerate(row):
                    c = cols[fam[label]].get(v)
                    if c:
                        for dy in range(scale):
                            for dx in range(scale):
                                px[(ox + x) * scale + dx, (1 + y) * scale + dy] = c
            ox += len(g[0]) + 2
    im.save(path)


def preview(path):
    from PIL import Image
    pal = {0: None, 1: (40, 30, 25), 2: (60, 110, 210), 3: (190, 140, 100), 4: (60, 110, 210),
           5: (40, 75, 150), 6: (60, 60, 80), 7: (20, 20, 20), 8: (230, 190, 40), 9: (50, 50, 55),
           10: (90, 90, 95), 11: (220, 220, 230)}
    sps = sprites()
    scale = 8
    im = Image.new("RGB", (len(sps) * 18 * scale, 18 * scale), (96, 140, 78))
    px = im.load()
    for n, sp in enumerate(sps):
        for y, row in enumerate(sp):
            for x, v in enumerate(row):
                c = pal[v]
                if c:
                    for dy in range(scale):
                        for dx in range(scale):
                            px[(n * 18 + 1 + x) * scale + dx, (1 + y) * scale + dy] = c
    im.save(path)


if __name__ == "__main__":
    sp = sprites()
    print(f"ok: {len(sp)} sprites", file=sys.stderr)
    if len(sys.argv) > 2 and sys.argv[1] == "--write":
        src = open(sys.argv[2]).read()
        a = src.index(";; ---- SPRITE DATA")
        b = src.index(";; ---- END SPRITE DATA ----") + len(";; ---- END SPRITE DATA ----")
        open(sys.argv[2], "w").write(src[:a] + nasm() + src[b:])
    elif len(sys.argv) > 2 and sys.argv[1] == "--preview":
        preview(sys.argv[2])
    elif len(sys.argv) > 2 and sys.argv[1] == "--preview-objects":
        preview_objects(sys.argv[2])
    else:
        print(nasm())
