#!/usr/bin/env python3
"""The player's vehicles' art (10.06), and the trig table they steer by.

A vehicle is drawn from a few shapes in its own frame of reference
(x along its length, pointing where it's heading; y across), then
rendered at VEHICLE_FACINGS headings by sampling each output pixel's
centre, rotated back into that frame. So there's one drawing per
vehicle, not sixteen.

Writes the block between the VEHICLE ART markers of a step's
vehicle_art.asm:

    python3 tools/gen_vehicles.py --write 06_bicycle/vehicle_art.asm
    python3 tools/gen_vehicles.py --preview bikes.png
"""
import math, sys

FACINGS = 16          # headings drawn; the game's heading is 0..255
SIZE = 24             # each facing: SIZE x SIZE pixels, centred

# palette slots, filled in by the game: 1 tyre, 2 frame, 3 metal, 4 saddle
# (longer than the 16 px rider on top of it, so the wheels and the bars
# show past him)
BICYCLE = [
    # (kind, x0, y0, x1, y1, slot): rectangles in the bike's frame, px,
    # centre at 0,0, the front toward +x
    ("rect", 5.0, -1.0, 11.5, 1.0, 1),    # front tyre
    ("rect", -11.5, -1.0, -5.0, 1.0, 1),  # back tyre
    ("rect", -7.0, -0.7, 7.0, 0.7, 2),    # frame
    ("rect", 6.0, -5.2, 7.4, 5.2, 3),     # handlebars
    ("rect", -4.4, -1.4, -1.6, 1.4, 4),   # saddle
]


def sample(shapes, x, y):
    v = 0
    for kind, x0, y0, x1, y1, slot in shapes:
        if x0 <= x <= x1 and y0 <= y <= y1:
            v = slot                        # later shapes on top
    return v


def facings(shapes):
    out = []
    for f in range(FACINGS):
        a = 2 * math.pi * f / FACINGS       # 0 = east, clockwise (y down)
        c, s = math.cos(a), math.sin(a)
        grid = []
        for py in range(SIZE):
            row = []
            for px in range(SIZE):
                dx, dy = px + 0.5 - SIZE / 2, py + 0.5 - SIZE / 2
                # screen -> bike frame: rotate by -a
                bx, by = dx * c + dy * s, -dx * s + dy * c
                row.append(sample(shapes, bx, by))
            grid.append(row)
        out.append(grid)
    return out


def nasm():
    out = [";; ---- VEHICLE ART (generated by tools/gen_vehicles.py; don't edit by hand) ----",
           f"VEHICLE_FACINGS equ {FACINGS}",
           f"VEHICLE_SPRITE equ {SIZE}          ; each facing is this square, centred on the vehicle",
           "", "section .data",
           "    ; the bicycle, at 16 headings (0 east, then clockwise), palette slots:",
           "    ; 1 tyre, 2 frame, 3 metal, 4 saddle"]
    out.append("    bicycle_sprites:")
    for f, grid in enumerate(facings(BICYCLE)):
        out.append(f"        ; heading {f * 360 // FACINGS} degrees")
        for row in grid:
            out.append("        db " + ",".join(str(v) for v in row))
    out.append("    ; sin_table[a] = sin(a * 2 pi / 256) * 256, a = 0..255 (cos: a + 64)")
    out.append("    sin_table:")
    vals = [round(math.sin(a * 2 * math.pi / 256) * 256) for a in range(256)]
    for i in range(0, 256, 16):
        out.append("        dw " + ", ".join(str(v) for v in vals[i:i + 16]))
    out.append(";; ---- END VEHICLE ART ----")
    return "\n".join(out)


def preview(path):
    from PIL import Image
    pal = {0: (96, 140, 78), 1: (20, 20, 20), 2: (200, 40, 40), 3: (170, 170, 175), 4: (60, 40, 30)}
    fs = facings(BICYCLE)
    im = Image.new("RGB", (SIZE * FACINGS, SIZE))
    for f, grid in enumerate(fs):
        for y, row in enumerate(grid):
            for x, v in enumerate(row):
                im.putpixel((f * SIZE + x, y), pal[v])
    im.resize((SIZE * FACINGS * 4, SIZE * 4), Image.NEAREST).save(path)


if __name__ == "__main__":
    if len(sys.argv) > 2 and sys.argv[1] == "--write":
        src = open(sys.argv[2]).read()
        a = src.index(";; ---- VEHICLE ART")
        b = src.index(";; ---- END VEHICLE ART ----") + len(";; ---- END VEHICLE ART ----")
        open(sys.argv[2], "w").write(src[:a] + nasm() + src[b:])
    elif len(sys.argv) > 2 and sys.argv[1] == "--preview":
        preview(sys.argv[2])
    else:
        print(nasm())
